version: '3.7'

networks:
  aw-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    networks:
      - aw-network
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    networks:
      - aw-network