global:
  scrape_interval: 5s
#  evaluation_interval: 15s
#
#  external_labels:
#    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: "api-registration-job"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api-registration"